export const languages = ["zh-Hans", "ja", "en"];
export const strings = {
  "zh-Hans": {
    title: "BalloonBarrage 气球弹幕｜游戏与开发近况",
    description: "在暖色工作室里用颜料弹击破气球。查看气球弹幕的当前原型、开发近况、九大祭展示计划和 Windows 试玩发布状态。",
    skip: "跳到正文", navigation: "页面导航", navGame: "玩法", navFestival: "九大祭", navArt: "美术", navDownload: "试玩", language: "语言",
    eyebrow: "气球弹幕",
    intro: "一款用油漆枪打气球的小型射击游戏。场景是一间有阳光、植物和颜料罐的工作室。",
    heroMore: "看看当前原型", heroDownload: "试玩发布状态", prototype: "开发中 · Windows 单人原型",
    gameTitle: "瞄准气球，按住左键。",
    gameIntro: "场上同时有三个气球。击破一个后，稍等片刻就会补上新的；命中会计分，颜料弹与爆裂碎片也已经接入原型。",
    prototypeCaption: "当前原型 · Unity 相机画面（不含界面）",
    prototypeAlt: "当前原型的工作室画面：三个青色气球、木质靶区、庭院窗景、植物和右下角的油漆枪",
    controlsTitle: "原型操作", mouseLabel: "移动鼠标", buttonLabel: "按住左键", controlsAim: "瞄准", controlsFire: "连续发射颜料弹",
    sceneNote: "工作室里加上了庭院窗景、工作台和绿植，配乐也换成了柔和的键盘声与轻鼓点。画面和射击手感还会继续调整。",
    developmentTitle: "接下来要做的",
    developmentBody: "展示版想做成 90 秒一局。多球与连射已经完成，接下来补齐计时、结算、重开和日文操作提示，再到展示电脑上检查离线运行。",
    laterBody: "波次、随机强化、手柄、本地双人和游戏内三语切换，留到展示版之后。官网的三语页面已可以使用。",
    festivalTitle: "九大祭展示计划",
    festivalBody: "我是九州大学创作社团 Qpic 的成员，正在为九大祭准备这款游戏的单人试玩。计划在 10 月 31 日带去展示，欢迎到时来试试。",
    festivalDateLabel: "计划展示日期", festivalDate: "2026 年 10 月 31 日", festivalVenue: "九州大学 · 伊都校区",
    festivalNote: "展位与试玩时段还没确定，确认后会更新在这里。", qpicLink: "Qpic 社团网站", festivalLink: "九大祭官方网站",
    artTitle: "美术草案", artIntro: "工作室、油漆枪和气球的早期设计参考。这里是概念图，当前原型画面在上方。",
    artStudio: "工作室的光线与配色", artGun: "油漆枪造型", artBalloon: "气球的形状与颜色", artLabel: "概念图",
    artOpen: "查看大图", artClose: "关闭大图",
    studioAlt: "工作室概念图：木质框架、彩色气球和墙上的青色与珊瑚色喷漆",
    gunAlt: "油漆枪概念图：青色颜料罐、奶油色枪身与珊瑚色枪口",
    balloonAlt: "珊瑚红、青色和靛蓝色气球的造型参考图",
    downloadTitle: "Windows 试玩", downloadIntro: "试玩包会在完成回合流程、通过运行检查后免费发布。下载和版本说明都放在 GitHub Releases。",
    downloadPlatform: "Windows · 键盘与鼠标", downloadEmpty: "还没有公开试玩包",
    downloadEmptyBody: "当前仍在开发原型。发布后，这里会显示 Windows 包的下载链接与版本信息。",
    downloadUnknown: "暂时无法确认发布状态", downloadUnknownBody: "请到 GitHub Releases 查看最新发布。",
    downloadReady: "下载 Windows 试玩包", downloadRelease: "查看发布列表", downloadSource: "源代码与开发记录",
    downloadInstructions: "完整解压 ZIP 后，运行文件夹内的 BalloonBarrage.exe。请保留旁边的数据文件夹；实际文件名以发布说明为准。",
    downloadBuild: "版本", downloadSize: "大小", downloadPreview: "预发布试玩版", downloadNotes: "发布说明",
    feedback: "问题与建议 → GitHub Issues", footer: "BalloonBarrage · 气球弹幕", footerNote: "正在准备九大祭单人试玩。",
    credits: "美术与音频来源", privacy: "本站不使用广告或访问统计。",
    creditsBody: "概念图、菜单插画与部分场景纹理使用 AI 辅助生成；配乐为项目原创合成音乐。Balloon 模型：Poly by Google / Poly Pizza（CC-BY）；Blaster Kit 与 Impact Sounds：Kenney（CC0）。完整来源及待核对的许可项见素材记录。",
    creditsLink: "查看完整素材记录", noScript: "语言切换和下载链接无需 JavaScript。关闭 JavaScript 时，图片链接会直接打开原图。"
  },
  ja: {
    title: "BalloonBarrage｜ゲーム紹介と開発状況",
    description: "日差しの入るアトリエで、ペイントガンを使って風船を割るゲーム。現在のプロトタイプ、開発状況、九大祭への出展予定、Windows 体験版の配信情報。",
    skip: "本文へ移動", navigation: "ページ内ナビゲーション", navGame: "遊び方", navFestival: "九大祭", navArt: "アート", navDownload: "体験版", language: "言語",
    eyebrow: "ペイントガンで風船割り",
    intro: "日差しの入るアトリエで、風船を割る小さなシューティングゲーム。植物や絵の具缶に囲まれて、ペイントガンで的を狙います。",
    heroMore: "プロトタイプを見る", heroDownload: "体験版の配信状況", prototype: "開発中 · Windows 向けソロプレイ",
    gameTitle: "風船を狙って、左ボタンを押し続ける。",
    gameIntro: "風船は同時に3つ。割ると少し待って新しい風船が現れ、命中するたびにスコアが増えます。ペイント弾と破裂時の破片も実装済みです。",
    prototypeCaption: "現在のプロトタイプ · Unity のカメラ画像（UIなし）",
    prototypeAlt: "現在のアトリエのプロトタイプ。青緑の風船3つ、木製の的枠、中庭が見える窓、植物、右下のペイントガン",
    controlsTitle: "プロトタイプの操作", mouseLabel: "マウス移動", buttonLabel: "左ボタン長押し", controlsAim: "照準を動かす", controlsFire: "ペイント弾を連射する",
    sceneNote: "窓の外の中庭、作業台、観葉植物を加えました。BGM も柔らかい鍵盤の音と軽いドラムに変更。見た目と撃ち心地は引き続き調整していきます。",
    developmentTitle: "次に作るもの",
    developmentBody: "展示版は1プレイ90秒を目指しています。風船の補充と連射は実装済み。次はタイマー、リザルト、リトライ、日本語の操作案内を揃え、展示用 PC でオフライン動作を確認します。",
    laterBody: "ウェーブ、ランダム強化、ゲームパッド、ローカル2人プレイ、ゲーム内の3言語切替は展示版の後に。公式サイトはすでに3言語で読めます。",
    festivalTitle: "九大祭への出展予定",
    festivalBody: "九州大学の創作サークル Qpic に所属しています。九大祭に向けて、このゲームのソロ体験版を制作中です。10月31日に展示する予定なので、ぜひ遊びに来てください。",
    festivalDateLabel: "出展予定日", festivalDate: "2026年10月31日", festivalVenue: "九州大学 · 伊都キャンパス",
    festivalNote: "展示場所と試遊時間はまだ未定です。決まり次第、ここでお知らせします。", qpicLink: "Qpic のサイト", festivalLink: "九大祭公式サイト",
    artTitle: "初期デザイン", artIntro: "アトリエ、ペイントガン、風船の初期デザインです。ここはコンセプトアートで、現在のプロトタイプの画像は上に掲載しています。",
    artStudio: "アトリエの光と色", artGun: "ペイントガンの形", artBalloon: "風船の形と色", artLabel: "コンセプトアート",
    artOpen: "画像を拡大", artClose: "拡大画像を閉じる",
    studioAlt: "アトリエのコンセプト。木製の枠、カラフルな風船、青緑とコーラルのペイントが付いた壁",
    gunAlt: "青緑の絵の具タンク、クリーム色の本体、コーラル色の銃口を持つペイントガンのコンセプト",
    balloonAlt: "コーラル、青緑、インディゴの風船のデザイン資料",
    downloadTitle: "Windows 体験版", downloadIntro: "ラウンドの流れを完成させ、動作確認を終えてから無料で公開します。ダウンロードと更新内容は GitHub Releases に掲載します。",
    downloadPlatform: "Windows · キーボードとマウス", downloadEmpty: "体験版はまだ公開していません",
    downloadEmptyBody: "現在はプロトタイプを開発中です。公開後、ここに Windows 版のダウンロードリンクとバージョン情報を掲載します。",
    downloadUnknown: "配信状況を確認できません", downloadUnknownBody: "最新の配信情報は GitHub Releases でご確認ください。",
    downloadReady: "Windows 体験版をダウンロード", downloadRelease: "リリース一覧を見る", downloadSource: "ソースコードと開発記録",
    downloadInstructions: "ZIP をすべて展開し、フォルダー内の BalloonBarrage.exe を起動してください。隣のデータフォルダーはそのままにしてください。実際のファイル名はリリースノートをご確認ください。",
    downloadBuild: "バージョン", downloadSize: "サイズ", downloadPreview: "プレリリース体験版", downloadNotes: "リリースノート",
    feedback: "不具合・ご意見 → GitHub Issues", footer: "BalloonBarrage", footerNote: "九大祭に向けてソロ体験版を制作中。",
    credits: "アート・音声の出典", privacy: "広告やアクセス解析は使用していません。",
    creditsBody: "コンセプトアート、メニューのイラスト、一部のテクスチャは AI を使って制作しています。BGM は本プロジェクトのオリジナル合成音楽です。Balloon モデル：Poly by Google / Poly Pizza（CC-BY）。Blaster Kit・Impact Sounds：Kenney（CC0）。全出典と確認が必要なライセンス項目は素材記録にまとめています。",
    creditsLink: "素材の記録を見る", noScript: "言語切替とダウンロードリンクは JavaScript なしでも使えます。JavaScript が無効の場合、画像リンクは原寸画像を開きます。"
  },
  en: {
    title: "BalloonBarrage | The game and development updates",
    description: "Pop balloons with a paint blaster in a sunlit studio. See the current BalloonBarrage prototype, development updates, planned Kyudai-sai exhibition, and Windows demo release status.",
    skip: "Skip to content", navigation: "Page navigation", navGame: "Gameplay", navFestival: "Exhibition", navArt: "Artwork", navDownload: "Demo", language: "Language",
    eyebrow: "A paint-blasting game",
    intro: "A small shooter about popping balloons with a paint blaster. The targets float in a sunlit studio, surrounded by plants, paint cans, and wooden shelves.",
    heroMore: "See the prototype", heroDownload: "Demo release status", prototype: "In development · Single-player · Windows",
    gameTitle: "Aim at a balloon. Hold the left button.",
    gameIntro: "Three balloons share the target area. Pop one and a new balloon appears after a short delay. Hits add to your score; paint projectiles and burst fragments are already working in the prototype.",
    prototypeCaption: "Current prototype · Unity camera capture (without UI)",
    prototypeAlt: "The current studio prototype with three teal balloons, a wooden target frame, a courtyard window, plants, and a paint blaster at the lower right",
    controlsTitle: "Prototype controls", mouseLabel: "Move the mouse", buttonLabel: "Hold left button", controlsAim: "Aim", controlsFire: "Fire paint continuously",
    sceneNote: "The studio now has a courtyard view, a workbench, and plants. The music has changed to soft keys and light drums. I'm still adjusting the scene and how shooting feels.",
    developmentTitle: "What I'm working on next",
    developmentBody: "The exhibition demo is planned around 90-second rounds. Multiple targets and held fire are in place. Next are the timer, results, retry, and Japanese instructions, followed by offline testing on the exhibition PC.",
    laterBody: "Waves, random upgrades, controllers, local co-op, and in-game language switching will come after the exhibition demo. The website is already available in three languages.",
    festivalTitle: "Plans for Kyudai-sai",
    festivalBody: "I'm a member of Qpic, Kyushu University's creative club. I'm preparing a single-player demo of this game for Kyudai-sai and plan to show it on October 31. Come try it if you're visiting.",
    festivalDateLabel: "Planned exhibition date", festivalDate: "October 31, 2026", festivalVenue: "Kyushu University · Ito Campus",
    festivalNote: "The booth and demo hours are still to be confirmed. I'll add them here once they're settled.", qpicLink: "Qpic's website", festivalLink: "Kyudai-sai website",
    artTitle: "Early designs", artIntro: "Early references for the studio, blaster, and balloons. These are concept images; the current prototype is shown above.",
    artStudio: "Studio lighting and colors", artGun: "Paint blaster design", artBalloon: "Balloon shapes and colors", artLabel: "Concept art",
    artOpen: "Enlarge image", artClose: "Close image",
    studioAlt: "Studio concept with wooden frames, colorful balloons, and teal and coral paint on the wall",
    gunAlt: "Paint blaster concept with a teal reservoir, cream body, and coral muzzle",
    balloonAlt: "Design reference for coral, teal, and indigo balloons",
    downloadTitle: "Windows demo", downloadIntro: "The demo will be free once the round flow is complete and the build has been tested. Downloads and update notes will be on GitHub Releases.",
    downloadPlatform: "Windows · Keyboard and mouse", downloadEmpty: "No public demo yet",
    downloadEmptyBody: "The prototype is still in development. Once a Windows build is published, its download link and version will appear here.",
    downloadUnknown: "Release status is unavailable", downloadUnknownBody: "Check GitHub Releases for the latest release information.",
    downloadReady: "Download Windows demo", downloadRelease: "View releases", downloadSource: "Source code and development notes",
    downloadInstructions: "Extract the entire ZIP, then run BalloonBarrage.exe inside the folder. Keep its data folder alongside it. Check the release notes for the actual executable name.",
    downloadBuild: "Version", downloadSize: "Size", downloadPreview: "Pre-release demo", downloadNotes: "Release notes",
    feedback: "Bugs and suggestions → GitHub Issues", footer: "BalloonBarrage", footerNote: "A solo demo in the works for Kyudai-sai.",
    credits: "Art and audio credits", privacy: "No ads or visitor analytics.",
    creditsBody: "Concept art, menu illustrations, and some scene textures were made with AI assistance. The music is original synthesis made for this project. Balloon model: Poly by Google / Poly Pizza (CC-BY). Blaster Kit and Impact Sounds: Kenney (CC0). The full source record also lists license details still to be verified.",
    creditsLink: "Full asset record", noScript: "Language and download links work without JavaScript. With JavaScript disabled, image links open the original images."
  }
};
