export const languages = ["zh-Hans", "ja", "en"];
export const strings = {
  "zh-Hans": {
    title: "BalloonBarrage 气球弹幕｜涂鸦射击游戏",
    description: "用油漆枪击破气球，让工作室充满色彩。BalloonBarrage 桌面射击游戏官方网站、开发进度和试玩下载。",
    skip: "跳到正文", navGame: "游戏", navFestival: "九大祭", navArt: "美术", navDownload: "下载", language: "语言",
    festivalBadge: "10.31 · 九大祭展示预告", festivalKicker: "QPIC · 九州大学物理研究部",
    festivalTitle: "10 月 31 日，九大祭见。", festivalBody: "作者是九州大学创作社团 Qpic 的成员。气球弹幕计划在九大祭展示，正在准备一局短小、爽快的 Windows 单人试玩。欢迎来瞄准、击破，留下你的最高分。",
    festivalDateLabel: "本作计划展示日期", festivalDate: "2026 年 10 月 31 日", festivalVenue: "九州大学 · 伊都校区",
    festivalNote: "具体展位与试玩时段将在确认后公布。", qpicLink: "认识 Qpic", festivalLink: "九大祭官方网站",
    eyebrow: "气球弹幕 · 桌面射击游戏", headline: "把快乐，喷成颜色。",
    intro: "带上油漆枪，走进涂鸦工作室。瞄准、发射、啪！让每一次击破都留下好心情。",
    heroDownload: "查看试玩下载", heroMore: "认识这间工作室", prototype: "开发中 · 当前为单人原型",
    edition: "WINDOWS 优先", gameKicker: "一点颜料，一大堆快乐", gameTitle: "不是战场，是你的涂鸦游乐场。",
    gameIntro: "暖色木框、鲜艳喷漆和圆滚滚的气球。我们正在把简单的击破，做成越打越痛快的桌面小游戏。",
    feature1Title: "颜料真的飞过去", feature1Body: "枪跟随鼠标瞄准，颜料弹飞向目标。命中后，气球爆裂、碎片散开、分数增加。",
    feature2Title: "让色彩占领工作室", feature2Body: "木质靶框、柔和光线和涂鸦喷溅。复用项目自己的环境、菜单与喷漆美术。",
    feature3Title: "把爽快继续加码", feature3Body: "先为九大祭做好多气球、连续射击和限时挑战；波次、随机强化、本地双人与手柄支持随后扩展。",
    available: "已有原型", direction: "美术方向", planned: "计划中",
    artKicker: "从我们的素材箱里", artTitle: "给每一次「啪」一点个性。",
    artIntro: "这些图来自本项目现有美术素材。概念图展示设计方向，不是当前游戏实机截图。",
    artStudio: "暖色涂鸦工作室", artGun: "卡通油漆枪", artBalloon: "气球造型与配色",
    artLabel: "概念美术", artOpen: "查看大图", artClose: "关闭大图",
    studioAlt: "暖色工作室概念图，墙上有青色与珊瑚色喷漆，空中漂浮着彩色气球",
    gunAlt: "青色颜料罐、奶油色枪身和珊瑚色枪口组成的卡通油漆枪概念图",
    balloonAlt: "珊瑚红、青色和靛蓝色气球的造型参考图",
    roadmapKicker: "下一桶颜料，正在调色", roadmapTitle: "先做好一局，再把快乐放大。",
    step1Title: "瞄准与击破", step1Body: "单人射击、飞行颜料弹、爆裂反馈、计分、生成等待和入场动画。",
    step2Title: "九大祭单人试玩", step2Body: "目标为 90 秒一局：多个气球、连射、日文操作提示、计时计分、结算与一键重开。",
    step3Title: "打包，带到九大祭", step3Body: "在展示电脑上验证离线运行；验收后，通过 GitHub Releases 提供 Windows 试玩包。",
    step4Title: "更多变化，更多朋友", step4Body: "展示后继续扩展波次、随机强化、三语切换、手柄和本地同屏双人。",
    done: "已接入原型", next: "下一阶段", later: "后续计划", releaseGate: "验收后发布",
    downloadKicker: "不经过商店，直接见面", downloadTitle: "把工作室带回家。",
    downloadIntro: "桌面版优先开发。试玩包会在 GitHub Releases 免费提供下载，无需商店账号。",
    downloadPlatform: "Windows · 桌面试玩", downloadEmpty: "试玩包准备中",
    downloadEmptyBody: "目前还没有公开的 Windows 试玩包。你可以先查看项目进度；发布后，这里会显示真实下载链接。",
    downloadUnknown: "暂时无法确认发布状态", downloadUnknownBody: "请到 GitHub Releases 查看是否已有可下载的试玩包。",
    downloadReady: "下载 Windows 试玩包", downloadRelease: "查看所有发布", downloadSource: "浏览源代码",
    downloadInstructions: "下载 ZIP 后完整解压，再运行文件夹内的 BalloonBarrage.exe；请保留旁边的数据文件夹。以发布说明中的文件名为准。",
    downloadBuild: "版本", downloadSize: "大小", downloadPreview: "预发布试玩版", downloadNotes: "发布说明",
    controlsTitle: "目前的原型操作", controlsAim: "移动鼠标：瞄准", controlsFire: "按住左键：连续发射颜料弹",
    controlsNote: "多球补充与连射已接入原型；完整回合、手柄、双人及游戏内三语切换仍在开发计划中。",
    feedback: "遇到问题？在 GitHub 提交反馈", footer: "BalloonBarrage · 气球弹幕",
    footerNote: "独立开发中。概念美术与当前原型可能不同。", credits: "素材署名", privacy: "本站不使用广告、分析统计或第三方字体。语言通过页面链接切换。",
    creditsBody: "项目模型与音效来源记录：Balloon — Poly by Google / Poly Pizza（CC-BY）；Blaster Kit 与 Impact Sounds — Kenney（CC0）。本页展示项目生成美术；完整许可与待核对项见仓库 CREDITS。",
    creditsLink: "完整素材来源与许可记录", noScript: "关闭 JavaScript 也可以浏览、切换语言和访问下载；图片放大需要 JavaScript。"
  },
  ja: {
    title: "BalloonBarrage｜カラフルなペイント・シューティング",
    description: "ペイントガンで風船を割って、アトリエを彩ろう。BalloonBarrage の公式サイト、開発状況、体験版ダウンロード。",
    skip: "本文へ移動", navGame: "ゲーム", navFestival: "九大祭", navArt: "アート", navDownload: "ダウンロード", language: "言語",
    festivalBadge: "10.31 · 九大祭に出展予定", festivalKicker: "QPIC · 九州大学物理研究部",
    festivalTitle: "10月31日、九大祭で会いましょう。", festivalBody: "作者は九州大学の創作サークル Qpic のメンバーです。九大祭での展示に向けて、短い時間で気持ちよく遊べる Windows 向けソロ体験版を制作中。狙って、割って、ハイスコアに挑戦してみませんか。",
    festivalDateLabel: "本作の出展予定日", festivalDate: "2026年10月31日", festivalVenue: "九州大学 · 伊都キャンパス",
    festivalNote: "展示場所と試遊時間は、決まり次第お知らせします。", qpicLink: "Qpicについて", festivalLink: "九大祭公式サイト",
    eyebrow: "BalloonBarrage · PC シューティング", headline: "楽しさを、色にしよう。",
    intro: "ペイントガンを持って、落書きアトリエへ。狙って、撃って、パーン！風船を割るたび、気分もカラフルに。",
    heroDownload: "体験版の配信状況", heroMore: "アトリエをのぞく", prototype: "開発中 · 現在はソロのプロトタイプ",
    edition: "WINDOWS 版を優先開発", gameKicker: "少しの絵の具、たくさんの楽しさ", gameTitle: "戦場じゃない。ここは色の遊び場。",
    gameIntro: "温かい木枠、鮮やかなペイント、まるい風船。シンプルな風船割りを、もっと気持ちのいい PC ゲームに育てています。",
    feature1Title: "絵の具が飛んでいく", feature1Body: "マウスに合わせて狙い、ペイント弾を発射。命中すると風船が割れ、破片が舞い、スコアが増えます。",
    feature2Title: "アトリエを彩ろう", feature2Body: "木製の的枠、柔らかな光、ペイントの飛沫。プロジェクトの環境・メニュー・スプレー素材を活用しています。",
    feature3Title: "もっと爽快に", feature3Body: "まずは九大祭に向けて、複数の風船・連射・タイムアタックを制作。ウェーブ、ランダム強化、ローカル協力プレイ、ゲームパッド対応はその後に。",
    available: "プロトタイプに実装", direction: "アートの方向性", planned: "計画中",
    artKicker: "アトリエの素材箱から", artTitle: "一つひとつの「パーン！」に個性を。",
    artIntro: "掲載画像は本プロジェクトの既存素材です。コンセプトアートは目指す方向であり、現在のゲーム画面ではありません。",
    artStudio: "温かな落書きアトリエ", artGun: "カートゥーンのペイントガン", artBalloon: "風船の形と色",
    artLabel: "コンセプトアート", artOpen: "画像を拡大", artClose: "拡大画像を閉じる",
    studioAlt: "カラフルな風船が浮かぶ温かなアトリエ。壁には青緑とコーラルのペイント",
    gunAlt: "青緑の絵の具タンク、クリーム色の本体、コーラル色の銃口を持つペイントガンのコンセプト",
    balloonAlt: "コーラル、青緑、インディゴの風船のデザイン資料",
    roadmapKicker: "次の色を、準備中", roadmapTitle: "まずは一回のプレイを、しっかり楽しく。",
    step1Title: "狙う、撃つ、割る", step1Body: "ソロ射撃、飛ぶペイント弾、破裂表現、スコア、再生成の待機と登場アニメーション。",
    step2Title: "九大祭のソロ体験版", step2Body: "1プレイ90秒を目標に、複数の風船、連射、日本語の操作案内、制限時間、スコア、リザルト、リトライを実装。",
    step3Title: "九大祭へ持っていこう", step3Body: "展示用 PC でオフライン動作を確認。検証後、GitHub Releases で Windows 体験版を配信。",
    step4Title: "遊びを広げよう", step4Body: "展示後はウェーブ、ランダム強化、3言語切替、ゲームパッド、ローカル2人プレイへ。",
    done: "原型に実装済み", next: "次の開発段階", later: "今後の計画", releaseGate: "確認後に公開",
    downloadKicker: "ストアを通さず、直接お届け", downloadTitle: "アトリエを、あなたの PC に。",
    downloadIntro: "PC 版を優先開発中。体験版は GitHub Releases から無料でダウンロードできます。ストアのアカウントは不要です。",
    downloadPlatform: "Windows · PC 体験版", downloadEmpty: "体験版を準備しています",
    downloadEmptyBody: "公開済みの Windows 体験版はまだありません。開発状況をご覧ください。配信後、ここにダウンロードリンクが表示されます。",
    downloadUnknown: "配信状況を確認できません", downloadUnknownBody: "ダウンロード可能な体験版があるか、GitHub Releases でご確認ください。",
    downloadReady: "Windows 体験版をダウンロード", downloadRelease: "すべてのリリース", downloadSource: "ソースコードを見る",
    downloadInstructions: "ZIP をすべて展開し、フォルダー内の BalloonBarrage.exe を起動してください。隣のデータフォルダーは移動せずに保管してください。実際のファイル名はリリースノートをご確認ください。",
    downloadBuild: "バージョン", downloadSize: "サイズ", downloadPreview: "プレリリース体験版", downloadNotes: "リリースノート",
    controlsTitle: "現在のプロトタイプの操作", controlsAim: "マウス移動：照準", controlsFire: "左ボタンを押し続ける：ペイント弾を連射",
    controlsNote: "複数の風船の補充と連射は実装済みです。ラウンド、ゲームパッド、協力プレイ、ゲーム内の3言語切替は開発予定です。",
    feedback: "不具合の報告は GitHub へ", footer: "BalloonBarrage",
    footerNote: "開発中のインディーゲームです。コンセプトアートと現在の原型は異なる場合があります。", credits: "素材のクレジット", privacy: "広告、アクセス解析、外部フォントは使用していません。ページのリンクで言語を切り替えます。",
    creditsBody: "モデル・音声の出典記録：Balloon — Poly by Google / Poly Pizza（CC-BY）、Blaster Kit・Impact Sounds — Kenney（CC0）。このページはプロジェクトの生成アートを使用しています。ライセンスと未確認事項はリポジトリの CREDITS をご覧ください。",
    creditsLink: "素材の出典とライセンス記録", noScript: "JavaScript が無効でも閲覧、言語切替、ダウンロードページへの移動が可能です。画像の拡大には JavaScript が必要です。"
  },
  en: {
    title: "BalloonBarrage | A colorful paint-blasting game",
    description: "Grab a paint blaster, pop balloons, and color the studio. The official BalloonBarrage website, development roadmap, and desktop demo downloads.",
    skip: "Skip to content", navGame: "The game", navFestival: "Exhibition", navArt: "The art", navDownload: "Downloads", language: "Language",
    festivalBadge: "Oct 31 · Planned Kyudai-sai showcase", festivalKicker: "QPIC · KYUSHU UNIVERSITY",
    festivalTitle: "See you at Kyudai-sai on October 31.", festivalBody: "The creator is a member of Qpic, Kyushu University's creative club. A short, satisfying Windows solo demo is in development for a planned Kyudai-sai showcase. Come aim, pop, and try for a high score.",
    festivalDateLabel: "Planned showcase date", festivalDate: "October 31, 2026", festivalVenue: "Kyushu University · Ito Campus",
    festivalNote: "Booth location and demo hours will be announced once confirmed.", qpicLink: "Meet Qpic", festivalLink: "Kyudai-sai official website",
    eyebrow: "BalloonBarrage · Desktop shooter", headline: "Make a happy little mess.",
    intro: "Grab your paint blaster and step into the graffiti studio. Aim, fire, pop! A little color. A very good time.",
    heroDownload: "Find the demo", heroMore: "Explore the studio", prototype: "In development · Solo prototype",
    edition: "WINDOWS FIRST", gameKicker: "A little paint. A lot of happy.", gameTitle: "Not a battlefield. Your colorful playground.",
    gameIntro: "Warm wooden frames, bright splashes, and round little balloons. We're turning a simple pop into a satisfying desktop game.",
    feature1Title: "Paint with a flight path", feature1Body: "Follow your mouse, aim the blaster, and send paint flying. A hit bursts the balloon, scatters fragments, and adds to your score.",
    feature2Title: "A studio full of color", feature2Body: "Wooden target frames, soft light, and graffiti splashes. Built around the project's own environment, menu, and paint artwork.",
    feature3Title: "More pops, more possibilities", feature3Body: "Multiple balloons, held fire, and a timed challenge come first for Kyudai-sai. Waves, random upgrades, local co-op, and controllers follow later.",
    available: "In the prototype", direction: "Art direction", planned: "Planned",
    artKicker: "From our art box", artTitle: "A little character in every pop.",
    artIntro: "These images are existing project artwork. Concept art shows the direction, not screenshots of the current game.",
    artStudio: "The cozy graffiti studio", artGun: "The cartoon paint blaster", artBalloon: "Balloon shapes and colors",
    artLabel: "Concept art", artOpen: "Enlarge image", artClose: "Close enlarged image",
    studioAlt: "A cozy studio with floating colorful balloons and teal and coral paint splashes on the wall",
    gunAlt: "A cartoon paint blaster concept with a teal reservoir, cream body, and coral muzzle",
    balloonAlt: "Design reference for coral, teal, and indigo balloons",
    roadmapKicker: "Mixing the next batch", roadmapTitle: "One good run. Then a whole lot more.",
    step1Title: "Aim. Paint. Pop.", step1Body: "Solo shots, flying paint, burst effects, scoring, respawn delay, and a smooth entrance.",
    step2Title: "A solo demo for Kyudai-sai", step2Body: "Targeting 90-second rounds with multiple balloons, held fire, Japanese instructions, a timer, scoring, results, and quick retry.",
    step3Title: "Ready for the exhibition", step3Body: "Verify offline play on the exhibition PC, then offer a tested Windows demo through GitHub Releases.",
    step4Title: "More variety, more friends", step4Body: "After the showcase: waves, random upgrades, in-game language switching, controllers, and shared-screen co-op.",
    done: "In the prototype", next: "Up next", later: "Later", releaseGate: "After testing",
    downloadKicker: "No storefront. Straight to your desktop.", downloadTitle: "Take the studio home.",
    downloadIntro: "Desktop comes first. Demo builds will be free to download through GitHub Releases. No store account needed.",
    downloadPlatform: "Windows · Desktop demo", downloadEmpty: "The demo is on its way",
    downloadEmptyBody: "There isn't a public Windows demo yet. Explore the project for now; a real download link will appear here once a build is published.",
    downloadUnknown: "Release status is unavailable", downloadUnknownBody: "Check GitHub Releases to see whether a downloadable demo is available.",
    downloadReady: "Download Windows demo", downloadRelease: "All releases", downloadSource: "Explore the source",
    downloadInstructions: "Extract the entire ZIP, then run BalloonBarrage.exe inside the folder. Keep its data folder alongside it. Check the release notes for the actual executable name.",
    downloadBuild: "Version", downloadSize: "Size", downloadPreview: "Pre-release demo", downloadNotes: "Release notes",
    controlsTitle: "Current prototype controls", controlsAim: "Move the mouse to aim", controlsFire: "Hold the left button to fire paint",
    controlsNote: "Multiple targets, refills, and held fire are implemented in the prototype. Full rounds, controllers, co-op, and in-game language switching are planned.",
    feedback: "Found an issue? Tell us on GitHub", footer: "BalloonBarrage",
    footerNote: "An indie game in development. Concept artwork may differ from the current prototype.", credits: "Asset credits", privacy: "No ads, analytics, or third-party fonts. Switch languages using the page links.",
    creditsBody: "Recorded model and audio sources: Balloon — Poly by Google / Poly Pizza (CC-BY); Blaster Kit and Impact Sounds — Kenney (CC0). This page uses project-generated artwork. See repository CREDITS for license records and outstanding checks.",
    creditsLink: "Full asset provenance and license records", noScript: "Browsing, language links, and downloads work without JavaScript. Enlarging artwork requires JavaScript."
  }
};
